CREATE TABLE [dbo].[Descriptionn]
(
	[ID] INT NOT NULL IDENTITY(1,1), 
    [Short] NVARCHAR(600) NOT NULL, 
    [Long] NVARCHAR(1500) NOT NULL,
	[Hotelid] INT NOT NULL,
	CONSTRAINT Pr_Key_DESC PRIMARY KEY([ID]),
	CONSTRAINT Ref_DESCRIPTION_HOTEL FOREIGN KEY([Hotelid]) REFERENCES Hotels(ID) ON DELETE CASCADE
)
